version: 2.1

jobs:
  sonarqube:
    docker:
      - image: circleci/node:14.17
    steps:
      - checkout
      - run:
          name: Install SonarQube Scanner
          command: |
            sudo npm install -g sonarqube-scanner
      - run:
          name: Run SonarQube Analysis
          command: sonar-scanner \                                                 
            -Dsonar.projectKey=godspeed \
            -Dsonar.sources=. \
            -Dsonar.host.url=https://sonarqube.alpha.blr.gluestack.app/

workflows:
  version: 2
  sonarqube:
    jobs:
      - sonarqube
