version: 2.1

jobs:
  sonarqube:
    docker:
      - image: circleci/node:14.17
    steps:
      - checkout
      - run:
          name: Install SonarQube Scanner
          command: sudo npm install -g sonarqube-scanner
      - run:
          name: Create SonarQube properties file
          command: |
            echo 'sonar.projectKey=godspeed' >> sonar-project.properties
            echo 'sonar.sources=.' >> sonar-project.properties
            echo 'sonar.host.url=https://sonarqube.alpha.blr.gluestack.app/' >> sonar-project.properties
            echo 'sonar.login=sqp_ff33e1c5bc07f305c5d553220e9f9f01eb3bd526' >> sonar-project.properties
      - run:
          name: Run SonarQube Analysis
          command: sonar-scanner -Dproject.settings=sonar-project.properties

workflows:
  version: 2
  sonarqube:
    jobs:
      - sonarqube
