version: 2.1

jobs:
  sonarqube:
    docker:
      - image: circleci/node:14.17
    steps:
      - checkout
      - run:
          name: Install SonarQube Scanner
          command: npm install -D sonar-scanner
      - run:
          name: Run SonarQube Analysis
          command: sonar-scanner \
            -Dsonar.projectKey=godspeed \
            -Dsonar.sources=. \
            -Dsonar.host.url=https://sonarqube.alpha.blr.gluestack.app/ \
            -Dsonar.login=sqp_ff33e1c5bc07f305c5d553220e9f9f01eb3bd526

workflows:
  version: 2
  sonarqube:
    jobs:
      - sonarqube
